name: "Run nixpkgs-review"

permissions: {}

on:
  workflow_dispatch:
    inputs:
      branch:
        description: The branch to checkout
        required: true
        type: string
      package:
        description: The package to build
        required: true
        type: string

jobs:
  review:
    name: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-26, macos-26-intel]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout nixpkgs
        uses: actions/checkout@v6
        with:
          repository: b5e596/nixpkgs
          ref: ${{ inputs.branch }}
          fetch-depth: 0

      - name: Get revision
        id: rev
        run: |
          set -euo pipefail
          echo "rev=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Install Nix (Linux)
        if: runner.os == 'Linux'
        uses: cachix/install-nix-action@v31.10.4
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install Nix (Darwin)
        if: runner.os == 'macOS'
        uses: cachix/install-nix-action@v31.10.4
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            sandbox = relaxed

      - name: Install tools
        run: |
          nix profile add nixpkgs#nixpkgs-review

      - name: Run nixpkgs-review
        run: |
          nixpkgs-review rev HEAD \
            --package ${{ inputs.package }} \
            --no-shell \
            --print-result \
            --build-args="-L"

      - name: Upload report
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: ~/.cache/nixpkgs-review/rev-${{ steps.rev.outputs.rev }}/report.md
